// node audio/music/test/calibrate.mjs [--write]
// Measures each instrument's reference passage with its trim at 0 dB and writes instruments/levels.mjs (trim per instrument in dB)
// so that every instrument sits at its target loudness (see LUFS_TARGET in lib.mjs): "unit mix" balance for the composers.
import fs from 'node:fs';
import path from 'node:path';
import { HERE, meter, refNotes, LUFS_TARGET, DEFAULT_TARGET, f } from './lib.mjs';
import * as inst from '../instruments.mjs';

const write = process.argv.includes('--write');
const levels = {};
for (const id of inst.list()) {
  const I = inst.INSTRUMENTS[id];
  const notes = refNotes(I);
  const last = Math.max(...notes.map((n) => n.t + (n.dur || 0.5)));
  const buf = I.render(notes, { seconds: Math.ceil(last + 6), gainDb: -I.gainDb });
  const l = meter.integratedLoudness(buf);
  const target = LUFS_TARGET[id] != null ? LUFS_TARGET[id] : DEFAULT_TARGET;
  let trim = target - l;
  // never let the trim push the peak of a vel-0.8 reference above -3 dBFS
  const pk = meter.peakDb(buf) + trim;
  if (pk > -3) trim -= pk + 3;
  levels[id] = Math.round(trim * 10) / 10;
  console.log(`${id.padEnd(16)} measured ${f(l)} LUFS  target ${target}  trim ${f(levels[id])} dB   peak after ${f(meter.peakDb(buf) + levels[id])} dBFS`);
}
if (write) {
  const out = `// GENERATED by test/calibrate.mjs - per-instrument loudness trim (dB). Do not edit by hand; re-run the calibration.\nexport default ${JSON.stringify(levels, null, 2)};\n`;
  fs.writeFileSync(path.join(HERE, '..', 'instruments', 'levels.mjs'), out);
  console.log('wrote instruments/levels.mjs');
}
