// node audio/music/test/gen_docs.mjs  -> writes audio/music/INSTRUMENTS.md from the live registry (so the table can never go stale)
import fs from 'node:fs';
import path from 'node:path';
import * as inst from '../instruments.mjs';
import { HERE, cues } from './lib.mjs';
import LEVELS from '../instruments/levels.mjs';

const esc = (s) => String(s).replace(/\|/g, '\\|');
const rowFor = (id) => {
  const I = inst.INSTRUMENTS[id];
  const opts = Object.entries(I.options || {}).map(([k, v]) => `\`${k}\` ${esc(v)}`).join('<br>');
  const defs = Object.keys(I.defaults || {}).length ? `<br>*defaults:* \`${esc(JSON.stringify(I.defaults))}\`` : '';
  const rg = I.range ? `${I.range[0]}-${I.range[1]}` : (I.kind === 'pitched' ? '' : I.defaultMidi != null ? `tuned ${I.defaultMidi}` : '-');
  const rv = `${I.reverb.preset} ${I.reverb.wet}`;
  const note = I.kind === 'drum' || I.kind === 'fx' ? (I.defaultDur != null ? `dur ${I.defaultDur} s` : '') : '';
  return `| \`${id}\` | ${esc(I.name)} | ${rg} | ${esc(I.desc)} | ${opts || '-'}${defs} | ${rv} | ${(LEVELS[id] ?? 0).toFixed(1)} |${note ? '' : ''}`;
};
const fam = [['keys', 'Keys and plucks'], ['strings', 'Strings'], ['brass', 'Brass'], ['winds', 'Woodwinds'], ['choir', 'Choir'], ['perc', 'Percussion'], ['synth', 'Synths'], ['fx', 'FX']];
let md = `# audio/music - instruments

Orchestra / band / FX palette for the 60 s film (\`audio/music/instruments.mjs\`). Pure Node ESM, deterministic (seeded per note), 48 kHz stereo float32 \`Buf\`s
from \`audio/lib\`. Everything is **dry with its own tasteful character**; reverb is applied by the composer on a bus (recommended preset per instrument below).
Generated by \`node audio/music/test/gen_docs.mjs\` from the live registry.

## Quick start

\`\`\`js
import * as inst from './instruments.mjs';
import * as th from '../lib/theory.mjs';          // motifEvents, chordNotes, chordForTime, arp, drumRoll helpers live here / below
import * as dsp from '../lib/dsp.mjs';

const mix = new dsp.Buf(60);
// 1. the motif once per bar on a piano, bars 2-10
const motif = th.motifBars([2, 3, 4], { vel: [0.9, 0.7, 0.75, 0.95] });                      // [{t, dur, midi, vel}] in film time
dsp.addAt(mix, inst.render('piano', motif, { gainDb: -2 }), 0);
// 2. a string pad on the chords with a swell, one reverb send for the bus
const pad = th.chordSpans(26, 42).flatMap((s) => th.chordNotes(s.name, 3, 'open').map((m) => ({ t: s.t0, dur: s.t1 - s.t0, midi: m, vel: 0.7 })));
const strings = inst.render('strings', pad, { art: 'legato' });
dsp.addAt(mix, strings, 0);
dsp.addAt(mix, inst.applySend(strings, 'strings'), 0);                                       // wet-only hall reverb, ADD it
// 3. a riser that lands on the 37.0 s orchestra hit
dsp.addAt(mix, inst.render('riser', [{ t: 35, dur: 2, vel: 0.9 }]), 0);
dsp.addAt(mix, inst.render('impact', [{ t: 37, vel: 1, size: 'L' }]), 0);
\`\`\`

## Notes (the only input format)

\`{ t, dur, midi, vel, pan?, gainDb?, ...instrument-specific }\` in **global film seconds**.

| field | meaning |
|---|---|
| \`t\` | onset (s). Slow-attack voices (strings legato, pads, choir, drone, shimmer, horns) are placed so that their *perceived* onset (about 30 % into the swell) is on \`t\`; the buffer starts earlier. Percussion / plucks start exactly at \`t\`. |
| \`dur\` | gate / key-down time. Each voice adds its own release tail after it (damper fall, bow release, reverb-friendly decay). Plucked/struck instruments ring naturally (\`harp\` ring 3.2 s, \`timpani\` until damped...). FX: \`dur\` = whole effect (riser builds for dur; impact tail; sub_drop length). |
| \`midi\` | pitch (A4 = 69 = 440 Hz). Drums: kick / snare / toms / timpani / taiko / sub808 are *tuned* by it (defaults sit in the key: kick A1, sub808 A1, timpani A2, taiko D2). Hats / clap / cymbal ignore it. |
| \`vel\` | 0..1 (default 0.8). Controls level **and brightness** (piano hammer, brass blat, bow pressure, snare wires, filter envelopes). |
| \`pan\` | -1..1 (default 0) added to the instrument's own stereo image. |
| \`gainDb\` | per-note trim. |

## render(id, notes, opts)

\`opts\`: \`seconds\` (buffer length, default 60 = cues.DURATION), \`buf\` (mix into an existing Buf instead of allocating), \`gainDb\`, \`pan\`, \`seed\` (default 1: change it to re-roll all the random micro-variation),
\`transpose\` (semitones), \`octave\`, \`segGap\` (s; notes closer than this share one bus pass, default 0.4), \`subHz\` (subsonic high-pass, default 22 Hz) + the per-instrument options in the tables.
Sparse parts are cheap: only the seconds that actually sound are processed (the rest of the Buf is digital silence).

## Loudness calibration

Every instrument carries a trim (\`gainDb\`, last column, generated by \`test/calibrate.mjs\`) so that its reference passage (4 spaced single notes at vel 0.8, or the standard groove for drums) measures
**-26 LUFS** integrated (percussion / FX offsets: kick -22, snare -24, snare_gated -23, hat -32, clap -25, toms -25, timpani -24, taiko -22, sub808 -24, cymbal -29, riser -27, reverse_swell -28, sub_drop -24, braam -20, impact -20, tape_rewind -33, shimmer -28).
That is a *unit balance*: a dozen layers sum to roughly the -17..-14 LUFS of the master. Chords stack (+3..6 dB for 3-4 voices): mix with \`gainDb\`.

## Instruments

Columns: id | name | playable midi range | description | options | recommended reverb (preset wet) | trim dB. Reverb presets are \`dsp.REVERB_PRESETS\` names; \`inst.applySend(bus, id)\` renders it wet-only.
`;
for (const [fk, title] of fam) {
  const ids = inst.list().filter((id) => inst.INSTRUMENTS[id].family === fk);
  if (!ids.length) continue;
  md += `\n### ${title}\n\n| id | name | range | description | options | reverb | trim |\n|---|---|---|---|---|---|---|\n${ids.map(rowFor).join('\n')}\n`;
}
md += `
## Helpers (notes generators)

| function | what |
|---|---|
| \`harpGliss(t, fromMidi, toMidi, {rootPc=0, scale='major'\\|pcs[], step=0.045, accel=0, vel=[0.45,0.8], dur=0.12})\` | diatonic glissando notes (C major / A minor by default), up or down; works for harp, celesta, music box, piano |
| \`windRun(t, fromMidi, toMidi, {step=BEAT/4, ...})\` | woodwind scale run (same engine, 16th-note steps) |
| \`drumRoll(t0, t1, {midi, rate=14, vel=[0.3,0.9], curve=1.6, humanize=0.18, seed, pan})\` | crescendo roll for timpani / snare / taiko / toms; last hit lands exactly on t1 |
| \`crashSignal(n, seed, {ring, bright, stationary})\` | the cymbal spectrum as a raw \`{L,R}\` (used by cymbal and reverse_swell) |
| \`reverbFor(id)\` / \`applySend(bus, id, {wetScale, tail, preset})\` | recommended reverb of an instrument; wet-only Buf to add to the mix |
| \`list()\` / \`info(id)\` | ids / metadata |

## Era processors (\`inst.processors.*\` or \`inst.PROCESSORS[name]\`), all \`(Buf, opts) -> new Buf\`, deterministic

| processor | options (defaults) | character |
|---|---|---|
| \`tapeWobble\` | wow 0.003, flutter 0.0006, drift 0.0015, wowRate 0.55, flutterRate 7.3, seed | varispeed wow & flutter; mean speed exactly 1 (no sync drift) |
| \`vinylCrackle\` | levelDb -26, rate 22, big 0.5, surface 1, seed | pops + surface noise added to the signal (\`crackleTexture(seconds, opts)\` = the texture alone) |
| \`reelHiss\` | levelDb -48 (RMS), hum false, seed | bright tape hiss |
| \`opticalSoundtrack\` | lo 140, hi 5200, mono 0.85, sat 1.25, flutter 0.0012, hissDb -50, seed | 1927 optical film sound: no lows, 5 kHz ceiling, nasal 2.5 kHz bump, saturation, flutter, hiss, near-mono (level-matched) |
| \`lofiPhone\` | lo 400, hi 4000, bits 11, rate 16000, drive 0.35, mono true | phone speaker: sample-rate/bit reduction -> 400 Hz-4 kHz mono -> saturation (level-matched) |
| \`brickwallBright\` | ceilingDb -1, airDb 2.2, driveDb 1.5, releaseMs 140 | modern: air shelf + soft clip + true-peak limiter |
| \`warmTape\` | drive 1.3, hfHz 12000, lowDb 1.2 | gentle tape saturation, low bump, rolled top |
| \`goldenAge\` | hi 10500 | 1930s-50s studio warmth + tiny wobble |
| \`monoize\` | amount 1 | collapse toward mono |

Run processors on the summed stem **after** the reverb send (the room should wobble and hiss with the music) and before the master limiter.

## ERA_STYLES: one arrangement kit per \`cues.ERAS[i].music\`

\`inst.ERA_STYLES[id]\` / \`inst.eraKit(cues.ERAS[i])\` (data in \`audio/music/presets.mjs\`). Same motif, same chords, same tempo: only the orchestration changes.
Fields: \`motifInstrument padInstrument rhythmInstrument\` (\`{id, opts, hint}\`, pad may be null), \`extras[]\` (\`{role, id, opts, hint}\`), \`processors[]\`, \`reverbPreset\`, \`mixDb {motif, pad, rhythm, master}\`.
Functions: \`kit.render(layer, notes, opts)\` (layer = motif | pad | rhythm | an extra's role), \`kit.send(buf)\` (wet-only era reverb), \`kit.process(buf)\` (era processors), \`kit.finish({motif: Buf, pad: Buf, ...}, {wetScale, process})\` (mixDb sum + send + processors + master).

| era music id | year | motif | pad | rhythm | extras | processors | reverb | mixDb |
|---|---|---|---|---|---|---|---|---|
`;
for (const e of cues.ERAS) {
  const k = inst.ERA_STYLES[e.music];
  const L = (x) => (x ? `\`${x.id}\`${Object.keys(x.opts || {}).length ? ' ' + esc(JSON.stringify(x.opts)) : ''}` : '-');
  md += `| \`${e.music}\` | ${e.year} | ${L(k.motifInstrument)} | ${L(k.padInstrument)} | ${L(k.rhythmInstrument)} | ${k.extras.map((x) => `${x.role}: \`${x.id}\``).join(', ') || '-'} | ${k.processors.map((p) => p.id).join(', ')} | ${k.reverbPreset.preset} ${k.reverbPreset.wet} | ${esc(JSON.stringify(k.mixDb))} |\n`;
}
md += `
Layer hints (what each era's composer is expected to write for each layer) are in \`presets.mjs\` (\`hint\` fields).

## Recipes

\`\`\`js
// the solo-piano turn (22.5-26.0): grand, pedal down, even quarter notes E G A C, C5 held into 26.0
inst.render('piano_grand', th.motifEvents(24.0, { rhythm: 'even', vel: [0.6, 0.55, 0.7, 0.8] }), { pedal: true });

// timpani roll into the baton-down hit at 37.0, then the hit
inst.render('timpani', inst.drumRoll(35, 37, { midi: 45, rate: 16, vel: [0.25, 0.95] }));
inst.render('cymbal', [{ t: 35, dur: 2, vel: 0.9, swell: true }]);        // peaks at 37.0

// harp glissando up into a downbeat, flute run
inst.render('harp', inst.harpGliss(11.4, 48, 84, { step: 0.04 }));
inst.render('flute', inst.windRun(10.5, 72, 91, { vel: [0.5, 0.85] }));

// era kit: 1960 brass + choir + timpani
const kit = inst.eraKit(cues.ERAS[4]);
const motifBuf = kit.render('motif', th.motifEvents(12, { octave: -1 }));
const padBuf = kit.render('pad', chordNotesAt12);
const out = kit.finish({ motif: motifBuf, pad: padBuf });
\`\`\`

## Tests and numbers (\`node audio/music/test/<file>\`)

| file | what |
|---|---|
| \`test_instruments.mjs\` | all 40 instruments: finite, peak <= -1 dBFS at vel 1, no DC, clean start/end, deterministic (in-process and across processes), sub-30 Hz content, fundamental within tolerance of the requested pitch (FFT peak / harmonic centroid for ensembles) at 4 registers, onset alignment, louder+brighter with velocity, register extremes |
| \`test_processors.mjs\` | tapeWobble (real wobble, mean pitch unchanged, no cumulative drift), hiss level, crackle density, optical / phone band limits, true peak of brickwallBright |
| \`calibrate.mjs [--write]\` | loudness trims -> \`instruments/levels.mjs\` |
| \`render_all.mjs [ids] [--png] [--sheet name]\` | the standard phrase (motif over Am then C) per instrument -> \`test/<id>.wav\` + spectrogram; contact sheets |
| \`note_sheet.mjs name id:midi:dur:vel ...\` | single-note linear spectrograms 0-8 kHz |
| \`demo_eras.mjs\` | the 9 era kits playing the motif over the era chord -> \`test/era_*.wav\`, \`eras_demo.wav\` + spectrogram |
| \`bench.mjs\` | render times of realistic full-film parts |
| \`gen_docs.mjs\` | regenerates this file |

### Known limits / design notes
* Synthesis only (modal / additive / subtractive / FM / formant); no samples. Strings/choir/brass are convincing *as a mix element behind reverb*, not as exposed solos.
* The choir sings vowels only (ooh/aah/eh/ee/oh and morphs); no consonants.
* \`dsp.limiter()\` (audio/lib/dyn.mjs) stamps a \`gain\` array on its result, which shadows \`Buf.gain(dB)\`; \`brickwallBright\` returns a clean Buf, composers calling \`limiter\` directly should rewrap with \`Buf.from(r.L, r.R)\`.
* Hard cuts (22.0 s) and the 60 s end are the composer's job (\`dsp.cutAt\`); instruments never write past \`opts.seconds\`.
`;
fs.writeFileSync(path.join(HERE, '..', 'INSTRUMENTS.md'), md);
console.log('wrote INSTRUMENTS.md', md.length, 'chars');
