#!/usr/bin/env node
// Generates audio/sfx/RECIPES.md from META (recipes_a.mjs) + the live cue list + measured solo stats.
//   node audio/sfx/test/make_docs.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import * as dsp from '../../lib/dsp.mjs';
import * as cues from '../../../shared/cues.js';
import { renderEvent, recipesA, recipesB, SPLIT } from '../index.mjs';
import { META } from '../recipes_a.mjs';
import { analyse } from './solo.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ids = Object.keys(recipesA).sort((a, b) => (cues.SFX.find((e) => e.id === a)?.t ?? 99) - (cues.SFX.find((e) => e.id === b)?.t ?? 99));
const f = (v, d = 1) => (Number.isFinite(v) ? v.toFixed(d) : '-inf');
let md = `# audio/sfx - sound-effect recipes

Everything is synthesised in code (no samples), deterministic (seeded RNG), 48 kHz stereo float32, timed from \`shared/cues.js\` (\`cues.SFX\`).
Generated by \`node audio/sfx/test/make_docs.mjs\` from \`META\` in \`recipes_a.mjs\` plus measured solo renders.

## Files

| file | role |
|---|---|
| \`index.mjs\` | dispatcher: \`recipes\`, \`renderSfx(cues)\`, \`renderEvent(ev, n)\`, \`coverage(cues)\`; imports \`recipes_b.mjs\` if present |
| \`render.mjs\` | \`renderSfx()\` -> \`audio/build/stems/sfx.wav\` + coverage table (also a CLI) |
| \`recipes_a.mjs\` | recipes for events with t < ${SPLIT} (this file) and the \`kit\` helper toolkit |
| \`recipes_b.mjs\` | (other agent) recipes for events with t >= ${SPLIT} |
| \`test/\` | \`solo.mjs\` (render every recipe to \`test/<id>.wav\` + spectrograms + metrics), \`stem_report.mjs\`, \`pitch_check.mjs\`, \`rhythm_check.mjs\`, \`make_docs.mjs\`, \`run_all.mjs\` |

## Recipe contract

\`recipes[id] = (ev, ctx) => Buf | { buf, offsetSec = 0, send = -14 }\`

* \`ev\` is the cue event \`{t, id, g?, pan?, dur?, ...params}\`; \`ctx = { ev, id, t, n, rng(label), seed(label), burst(win), cues, dsp }\`.
* Return a stereo \`dsp.Buf\` that **starts at the event time**. \`offsetSec\` = pre-roll: the cue time \`t\` is \`offsetSec\` seconds *into* the buffer (the dispatcher places it at \`t - offsetSec\`), used by reverse swells / whooshes that must land on \`t\`.
* \`send\` = dB into the shared gentle 'room' reverb send (\`-Infinity\` = none).
* The dispatcher applies \`ev.g\` (dB trim) and \`ev.pan\` (constant-power placement, unity centre). Recipes must not.
* Use \`ev.dur\` for sustained material (beds, loops); a tail may ring past it. Use \`ctx.rng(label)\` / \`ctx.seed(label)\` for randomness, never \`Math.random\`.
* Time-aware choice: for events with \`t < ${SPLIT}\` the \`recipes_a\` version of an id is preferred, at/after ${SPLIT} \`recipes_b\`. Unknown ids: soft fallback tick + loud warning.
* \`renderSfx\` ends with: shared room reverb, a 20 ms fade into 22.0 and **digital zero from 22.0 to 22.5** (read from \`cues.MUSIC.sections\` id 'silence'), and a transparent -1 dBTP limiter.
* \`import { kit } from './recipes_a.mjs'\` gives \`thump, modal, bellStrike, poisson, sweep, glideExp, wide, panSweep, widthEnv, put, verb, fin, dense, hzNearPc, chordAt ...\`.

## Levels and imaging (solo, measured)

Peak is the recipe's designed level before \`ev.g\`; \`Lk300\` = loudest 300 ms K-weighted level (perceptual proxy); \`S/M\` = side-to-mid energy (stereo width); \`corr\` = L/R correlation (mono compatibility).

| id | first cue | n | len s | peak dBFS | Lk300 dB | S/M dB | corr | description |
|---|---|---|---|---|---|---|---|---|
`;
const seen = new Map();
const rows = [];
for (const id of ids) {
  const evs = cues.SFX.filter((e) => e.id === id);
  const ev = evs[0];
  const r = renderEvent(ev, 0, cues);
  const buf = r.buf;
  const a = analyse(buf);
  rows.push({ id, ev, n: evs.length, a });
  md += `| \`${id}\` | ${ev.t} | ${evs.length} | ${f(a.len, 2)} | ${f(a.peakDb)} | ${f(a.lk300)} | ${f(a.sm, 0)} | ${f(a.corr, 2)} | ${(META[id] || '').replace(/\|/g, '/')} |\n`;
}
md += `\n## Coverage (cues.SFX)\n\n`;
const all = [...new Set(cues.SFX.map((e) => e.id))];
const have = (id) => !!(recipesA[id] || recipesB[id]);
md += `* ${all.length} distinct ids, ${cues.SFX.length} events; recipes_a covers ${ids.length} ids (all events with t < ${SPLIT}).\n`;
const missing = all.filter((id) => !have(id));
md += `* ids without a recipe right now: ${missing.length ? missing.map((m) => '\`' + m + '\`').join(', ') : 'none'}.\n`;
md += `\n## Cue list for t < ${SPLIT} (live)\n\n| t | id | g | pan | dur | other |\n|---|---|---|---|---|---|\n`;
for (const ev of cues.SFX.filter((e) => e.t < SPLIT)) {
  const { t, id, g, pan, dur, ...rest } = ev;
  md += `| ${t} | \`${id}\` | ${g ?? ''} | ${pan ?? ''} | ${dur ?? ''} | ${Object.keys(rest).length ? JSON.stringify(rest) : ''} |\n`;
}
fs.writeFileSync(path.join(HERE, '..', 'RECIPES.md'), md);
console.log('wrote audio/sfx/RECIPES.md', md.length, 'bytes');
void dsp;
